# Generated by Django 5.1.6 on 2025-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='tontines',
            field=models.ManyToManyField(blank=True, related_name='membres', to='membres.tontine'),
        ),
    ]
