# Generated by Django 5.1.6 on 2025-05-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_alter_membre_tontines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='tontines',
        ),
        migrations.AlterField(
            model_name='membre',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre_membres', to=settings.AUTH_USER_MODEL),
        ),
    ]
