# Generated by Django 5.1.6 on 2025-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_remove_membre_tontines_alter_membre_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='photo_cni',
            field=models.FileField(blank=True, null=True, upload_to='membres/cni/'),
        ),
    ]
