# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membretontine',
            name='tontine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine'),
        ),
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together={('cycle', 'ordre')},
        ),
    ]
