# Generated by Django 5.1.6 on 2025-05-08 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
