# Generated by Django 5.1.6 on 2025-05-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_remove_membre_tontines_alter_membre_utilisateur'),
        ('tontines', '0003_tontine_date_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontine',
            name='membres',
        ),
        migrations.AddField(
            model_name='tontine',
            name='createur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tontines_creees', to='membres.membre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribution',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='tontines.cycle'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tontines.tontine'),
        ),
        migrations.AlterField(
            model_name='membretontine',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_tontine', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='membretontine',
            name='tontine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_tontine', to='tontines.tontine'),
        ),
        migrations.AlterField(
            model_name='tontine',
            name='tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontines_gerees', to=settings.AUTH_USER_MODEL),
        ),
    ]
