# Generated by Django 5.1.6 on 2025-05-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0005_alter_tontine_tresorier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontine',
            name='createur',
        ),
    ]
