# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree_mois', models.IntegerField()),
                ('date_demande', models.DateField(default=django.utils.timezone.now)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('defaut', 'Défaut de paiement')], default='demande', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-date_demande'],
            },
        ),
    ]
