# Generated by Django 5.1.6 on 2025-05-08 15:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_remove_membre_tontines_alter_membre_utilisateur'),
        ('prets', '0001_initial'),
        ('tontines', '0004_remove_tontine_membres_tontine_createur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pret',
            options={},
        ),
        migrations.RemoveField(
            model_name='pret',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='duree_mois',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='motif',
        ),
        migrations.AddField(
            model_name='pret',
            name='approuve_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pret',
            name='tontine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prets_prets', to='tontines.tontine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pret',
            name='date_demande',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='date_echeance',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pret',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_prets', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('REMBOURSE', 'Remboursé'), ('EN_RETARD', 'En retard')], default='EN_COURS', max_length=10),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prets.pret')),
            ],
        ),
    ]
