# Generated by Django 5.1.6 on 2025-05-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0004_remove_tontine_membres_tontine_createur_and_more'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tontines',
            field=models.ManyToManyField(blank=True, related_name='customuser_tontines', to='tontines.tontine'),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_prevue', models.DateField()),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.cycle')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_utilisateurs', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.CharField(blank=True, help_text='Bénéficiaire du don si la tontine donne', max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_don', models.DateField()),
                ('sens_don', models.CharField(choices=[('ENTREE', 'Don reçu par la tontine'), ('SORTIE', 'Don fait par la tontine')], max_length=10)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('donateur', models.ForeignKey(blank=True, help_text='Personne qui fait le don', null=True, on_delete=django.db.models.deletion.CASCADE, to='tontines.membretontine')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_utilisateurs', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('REMBOURSE', 'Remboursé'), ('EN_RETARD', 'En retard')], default='EN_COURS', max_length=10)),
                ('approuve_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_utilisateurs', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_utilisateurs', to=settings.AUTH_USER_MODEL)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.pret')),
            ],
        ),
    ]
