# Generated by Django 5.1.6 on 2025-05-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_membre_photo_cni'),
        ('utilisateurs', '0002_customuser_tontines_cotisation_don_pret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='membre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prets_utilisateurs', to='membres.membre'),
            preserve_default=False,
        ),
    ]
