# Generated by Django 5.1.6 on 2025-05-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_membre_photo_cni'),
        ('utilisateurs', '0003_pret_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_utilisateur', to='membres.membre'),
        ),
    ]
