# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dons', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='membres.membre'),
        ),
    ]
