# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        ('prets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_interet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_prevue', models.DateField()),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='planifie', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='prets.pret')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
                ('remboursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remboursements.remboursement')),
            ],
        ),
    ]
