# Generated by Django 5.1.6 on 2025-05-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_prevue', models.DateField()),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('paye', 'Payée'), ('en_retard', 'En retard'), ('annule', 'Annulée')], default='planifie', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['date_prevue'],
            },
        ),
    ]
