# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisations', '0002_initial'),
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='tontines.tontine'),
        ),
    ]
