# Generated by Django 5.1.6 on 2025-05-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0002_initial'),
        ('operations', '0002_initial'),
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine'),
        ),
        migrations.AddField(
            model_name='don',
            name='donateur',
            field=models.ForeignKey(blank=True, help_text='Personne qui fait le don', null=True, on_delete=django.db.models.deletion.CASCADE, to='tontines.membretontine'),
        ),
        migrations.AddField(
            model_name='don',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='don',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine'),
        ),
        migrations.AddField(
            model_name='pret',
            name='approuve_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre'),
        ),
        migrations.AddField(
            model_name='pret',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.tontine'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.pret'),
        ),
    ]
