# Generated by Django 5.1.6 on 2025-05-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_remove_membre_tontines_alter_membre_utilisateur'),
        ('operations', '0003_initial'),
        ('tontines', '0004_remove_tontine_membres_tontine_createur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_operations', to='tontines.cycle'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_operations', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_operations', to='tontines.tontine'),
        ),
        migrations.AlterField(
            model_name='don',
            name='donateur',
            field=models.ForeignKey(blank=True, help_text='Personne qui fait le don', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dons_faits_operations', to='tontines.membretontine'),
        ),
        migrations.AlterField(
            model_name='don',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_enregistres_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='don',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_operations', to='tontines.tontine'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='approuve_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approuve_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pret',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_operations', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_operations', to='tontines.tontine'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enregistre_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_operations', to='operations.pret'),
        ),
    ]
