# Generated by Django 5.1.6 on 2025-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_cotisation_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='cni_justificatif',
            field=models.FileField(default='prets/cni/placeholder.pdf', upload_to='prets/cni/', verbose_name='Photocopie de la CNI'),
            preserve_default=False,
        ),
    ]
