# Generated by Django 5.1.6 on 2025-05-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_adhesiontontinedemande_demandecotisation_demandedon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecotisation',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='demandedon',
            name='donateur',
        ),
        migrations.RemoveField(
            model_name='demandepret',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='demanderemboursement',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='demanderemboursement',
            name='pret',
        ),
        migrations.DeleteModel(
            name='AdhesionTontineDemande',
        ),
        migrations.DeleteModel(
            name='DemandeCotisation',
        ),
        migrations.DeleteModel(
            name='DemandeDon',
        ),
        migrations.DeleteModel(
            name='DemandePret',
        ),
        migrations.DeleteModel(
            name='DemandeRemboursement',
        ),
    ]
